sky:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: j129333wb
  alioss:
    endpoint: oss-cn-hangzhou.aliyuncs.com
    access-key-id:
    access-key-secret:
    bucket-name: sky-jiang
  redis:
    host: localhost
    port: 6379
    database: 10

  wechat:
    appid: wx00cb65c3c80d555c
    secret: d466611052cd748052f0bfa980e19ad9
  baidu:
    ak:
  shop:
    address: 安徽省合肥市蜀山区潜山路470号
